name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Build
        run: make